before_script:
  - wget  https://github.com/wpilibsuite/allwpilib/releases/download/v2019.1.1/WPILib_Linux-2019.1.1.tar.gz -O /tmp/wpilib.tar.gz
  - tar -zxvf /tmp/wpilib.tar.gz

language:
  java

jdk:
  oraclejdk11
