// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5607.WeekendBuild;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftSpeedController;
    public static SpeedController drivetrainRightSpeedController;
    public static DifferentialDrive drivetrainDifferentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftSpeedController = new Spark(0);
        LiveWindow.addActuator("Drivetrain", "Left Speed Controller", (Spark) drivetrainLeftSpeedController);
        drivetrainLeftSpeedController.setInverted(false);
        drivetrainRightSpeedController = new Spark(1);
        LiveWindow.addActuator("Drivetrain", "Right Speed Controller", (Spark) drivetrainRightSpeedController);
        drivetrainRightSpeedController.setInverted(false);
        drivetrainDifferentialDrive1 = new DifferentialDrive(drivetrainLeftSpeedController, drivetrainRightSpeedController);
        LiveWindow.addActuator("Drivetrain", "Differential Drive 1", drivetrainDifferentialDrive1);
        drivetrainDifferentialDrive1.setSafetyEnabled(true);
        drivetrainDifferentialDrive1.setExpiration(0.1);
        drivetrainDifferentialDrive1.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
